shortName: ragllm
fullName: RAG-LLM
repo: https://github.com/validatedpatterns/rag-llm-gitops
webHookName: ''
owners:
  - mbaldess
triggers:
  branches:
  - name: main
    versions:
    - '4.16'

  openshift:
  - version: '4.16'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
