shortName: retail
fullName: Retail
repo: https://github.com/validatedpatterns/retail
webHookName: ''
owners:
  - mhjacks
triggers:
  branches:
  - name: main
    versions:
    - '4.14'

  openshift:
  - version: '4.13'
    branch: v1.1
    platforms:
      - aws
    buildType: stable

  - version: '4.12'
    branch: v1.1
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
